# Generated by Django 4.2 on 2024-01-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_key',
            field=models.IntegerField(blank=True, max_length=12, null=True, verbose_name='код подтверждения'),
        ),
    ]
