# Generated by Django 5.0 on 2024-01-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_for_one',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/'),
        ),
    ]
