# Generated by Django 4.2 on 2024-01-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_is_published', 'Может публиковать товары'), ('set_product_content', 'Может менять описание'), ('set_category', 'Может менять категорию')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
